# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
use_validation_for_early_stop: 1
val_freq: 1
key_score_metric: r100
convergence_threshold: 50
val_method: ""
val_batch_size: 4
file_val_set: ""

# Testing configuration
test_method: ""
test_batch_size: 4
file_test_set: ""

# DataLoader configuration
Dataset_type: NodeListDataset
num_workers: 1
NodeListDataset_type: LinkDataset
pos_sampler: ObservedEdges_Sampler
neg_sampler: RandomNeg_Sampler
num_neg: 1
BatchSampleIndicesGenerator_type: SampleIndicesWithReplacement
train_batch_size: 2048
str_num_total_samples: num_edges
epoch_sample_ratio: 0.1

# Model configuration
model: ELPH
seed: 1999

device: "cuda:0"

dnn_arch: "[nn.Linear(64, 1024), nn.Tanh(), nn.Linear(1024, 1024), nn.Tanh(), nn.Linear(1024, 64)]"
dnn_lr: 0.001
loss_type: bpr

max_hash_hops: 2  # available: 1, 2, 3
minhash_num_perm: 128
hll_p: 8
use_zero_one: 1
