# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
use_validation_for_early_stop: 1
val_freq: 1
key_score_metric: r100
convergence_threshold: 20
val_method: ""
val_batch_size: 256
file_val_set: ""

# Testing configuration
test_method: ""
test_batch_size: 256
file_test_set: ""

# DataLoader configuration
Dataset_type: BlockDataset
num_workers: 0
num_gcn_layers: 2
train_num_layer_sample: "[10, 10]"
NodeListDataset_type: LinkDataset
pos_sampler: ObservedEdges_Sampler
neg_sampler: RandomNeg_Sampler
num_neg: 1
BatchSampleIndicesGenerator_type: SampleIndicesWithReplacement
train_batch_size: 1024
epoch_sample_ratio: 0.1

# Model configuration
model: GAMLP_learnable_emb
seed: 1999

graph_device: "cuda:0"
emb_table_device: "cuda:0"
gnn_device: "cuda:0"
out_emb_table_device: "cuda:0"

forward_mode: sample

emb_dim: 64
emb_lr: 0.005
GAMLP_type: GAMLP_JK
gnn_lr: 0.001
emb_init_std: 0.1
use_sparse: 0
freeze_emb: 0
from_pretrained: 1
file_pretrained_emb: ''

GAMLP_type: GAMLP_JK
hidden: 512
n_layers_1: 4
n_layers_2: 4
pre_process: 0
residual: 0
bns: 0
dnn_lr: 0.001

L2_reg_weight: 0.0
loss_type: bpr
