model: gamlp_learnable_emb
train_dl: EdgeBased_Sampling_Block_TrainDataLoader

device: 'cuda:0'

convergence_threshold: 5
val_freq: 1
key_score_metric: r100
epochs: 200

train_batch_size: 1024
ensure_neg_is_not_neighbor: 0
num_workers: 6

validation_method: ''
mask_nei_when_validation: 0
file_validation: ''

test_method: ''
mask_nei_when_test: 1
file_test: ''

emb_dim: 64
emb_lr: 0.005
GAMLP_type: GAMLP_JK
gnn_lr: 0.001
emb_init_std: 0.1
use_sparse: 0
freeze_emb: 0
from_pretrained: 1
file_pretrained_emb: ''

num_gcn_layers: 1
num_layer_sample: '[]'

loss_fn: bpr_loss
num_neg: 1
