# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
use_validation_for_early_stop: 1
val_freq: 1
key_score_metric: r100
convergence_threshold: 20
val_method: ""
val_batch_size: 256
file_val_set: ""

# Testing configuration
test_method: ""
test_batch_size: 256
file_test_set: ""

# DataLoader configuration
Dataset_type: NodeListDataset
num_workers: 1
NodeListDataset_type: LinkDataset
pos_sampler: ObservedEdges_Sampler
neg_sampler: RandomNeg_Sampler
num_neg: 1
BatchSampleIndicesGenerator_type: SampleIndicesWithReplacement
train_batch_size: 2048
epoch_sample_ratio: 0.1

# Model configuration
model: GBP
seed: 1999
device: 'cuda:0'

from_pretrained: 1
file_pretrained_emb: ''
freeze_emb: 1

alpha: 0.1
walk_length: 6
rmax_ratio: 0.01
dnn_arch: "[nn.Linear(64, 1024), nn.Tanh(), nn.Linear(1024, 64)]"
dnn_lr: 0.001
L2_reg_weight: 0.0

loss_fn: bpr
