# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
use_validation_for_early_stop: 1
val_freq: 1
key_score_metric: r100
convergence_threshold: 20
val_method: ""
val_batch_size: 256
file_val_set: ""

# Testing configuration
test_method: ""
test_batch_size: 256
file_test_set: ""

# Model configuration
model: GensimNode2vec
seed: 1999

emb_dim: 64
emb_lr: 0.01
num_walks: 16
walk_length: 16
p: 1.0
q: 1.0
context_size: 5
num_neg: 5

num_workers: 6
