model: node2vec

device: 'cuda:0'
num_workers: 6

convergence_threshold: 20
val_freq: 1
key_score_metric: r100
epochs: 200

train_batch_size: 2048

emb_dim: 64
emb_lr: 0.005

walk_length: 12
num_walks: 8
context_size: 5
p: 1.0
q: 1.0
num_neg: 4
