# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
use_validation_for_early_stop: 1
val_freq: 1
key_score_metric: r100
convergence_threshold: 20
val_method: ""
val_batch_size: 256
file_val_set: ""

# Testing configuration
test_method: ""
test_batch_size: 256
file_test_set: ""

# DataLoader configuration
train_batch_size: 2048
num_workers: 4

# Model configuration
model: Node2vec
seed: 1999
device: cpu
emb_dim: 64
emb_lr: 0.005
walk_length: 12
num_walks: 8
context_size: 5
p: 1.0
q: 1.0
num_neg: 4
