model: sgc
train_dl: EdgeBased_Sampling_TrainDataLoader

device: 'cuda:0'

convergence_threshold: 20
val_freq: 1
key_score_metric: r100
epochs: 200

train_batch_size: 1024
ensure_neg_is_not_neighbor: 0

validation_method: ''
mask_nei_when_validation: 0
file_validation: ''

test_method: ''
mask_nei_when_test: 1
file_test: ''

from_pretrained: 1
file_pretrained_emb: ''
freeze_emb: 1

l2_reg_weight: 0.0
dnn_lr: 0.001

num_gcn_layers: 2

loss_fn: bpr_loss
num_neg: 1
# loss_fn: ssm_loss  # in-batch neg
# tao: 0.2
# num_neg: 0
