# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
val_freq: 1
key_score_metric: r100
convergence_threshold: 20

# DataLoader configuration
Dataset_type: NodeListDataset
num_workers: 1
NodeListDataset_type: LinkDataset
pos_sampler: ObservedEdges_Sampler
neg_sampler: RandomNeg_Sampler
num_neg: 1
BatchSampleIndicesGenerator_type: SampleIndicesWithReplacement
train_batch_size: 2048
train_edge_sample_ratio: 0.1

# Evaluator configuration
val_evaluator: ""
val_batch_size: 256
file_val_set: ""
test_evaluator: ""
test_batch_size: 256
file_test_set: ""

# Model configuration
model: SIGN
seed: 1999
device: 'cuda:0'

from_pretrained: 1
file_pretrained_emb: ''
freeze_emb: 1

L2_reg_weight: 0.0
dnn_lr: 0.001

num_gcn_layers: 2
num_dnn_layers: 2

loss_fn: bpr
