model: simplex
train_dl: EdgeBased_Sampling_TrainDataLoader

convergence_threshold: 20
val_freq: 1
key_score_metric: r100
epochs: 200

device: 'cuda:0'

train_batch_size: 1024
ensure_neg_is_not_neighbor: 0

num_neg: 64
neg_weight: 64

emb_dim: 64
emb_init_std: 0.1
emb_lr: 0.001
freeze_emb: 0
from_pretrained: 0

margin: 0.4
theta: 0.5
l2_reg_weight: 0.0001

use_uniform_weight: 1

validation_method: ''
mask_nei_when_validation: 0
file_validation: ''

test_method: ''
mask_nei_when_test: 1
file_test: ''
