# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
val_freq: 1
key_score_metric: r100
convergence_threshold: 20

# DataLoader configuration
Dataset_type: NodeListDataset
num_workers: 1
NodeListDataset_type: LinkDataset
pos_sampler: ObservedEdges_Sampler
neg_sampler: RandomNeg_Sampler
num_neg: 256
BatchSampleIndicesGenerator_type: SampleIndicesWithReplacement
train_batch_size: 1024
epoch_sample_ratio: 0.1

# Evaluator configuration
val_evaluator: ""
val_batch_size: 256
file_val_set: ""
test_evaluator: ""
test_batch_size: 256
file_test_set: ""

# Model configuration
model: SimpleX
seed: 1999

device: "cuda:0"

neg_weight: 256

train_num_layer_sample: "[]"

emb_dim: 64
emb_init_std: 0.1
emb_lr: 0.001
use_sparse: 1
freeze_emb: 0
from_pretrained: 0

margin: 0.4
theta: 0.5
L2_reg_weight: 0.0001

use_uniform_weight: 1
