model: UltraGCN

Dataset_type: NodeListDataset
num_workers: 1

NodeListDataset_type: LinkDataset
pos_sampler: ObservedEdges_Sampler
neg_sampler: RandomNeg_Sampler
num_neg: 1

BatchSampleIndicesGenerator_type: SampleIndicesWithReplacement
train_batch_size: 2048
train_edge_sample_ratio: 0.1

emb_lr: 0.001
emb_dim: 64
emb_init_std: 0.0001
freeze_emb: 0
from_pretrained: 0
file_pretrained_emb: ''
l2_reg_weight: 0.0

loss_fn: bce_loss
num_neg: 64
neg_weight: 64

topk: 8
lambda: 0.8
gamma: 1.5
l2_reg_weight: 0.0001

freeze_emb: 0
from_pretrained: 0
use_sparse: 1
