model: ultragcn
train_dl: EdgeBased_Sampling_TrainDataLoader

convergence_threshold: 20
val_freq: 1
key_score_metric: r100
epochs: 200

train_batch_size: 2048
ensure_neg_is_not_neighbor: 0

emb_lr: 0.001
emb_dim: 64
emb_init_std: 0.0001
freeze_emb: 0
from_pretrained: 0
file_pretrained_emb: ''
l2_reg_weight: 0.0

loss_fn: bce_loss
num_neg: 64
neg_weight: 64

topk: 8
lambda: 0.8
gamma: 1.5
l2_reg_weight: 0.0001

freeze_emb: 0
from_pretrained: 0
use_sparse: 1

device: 'cuda:0'
