# Dataset/Results root
data_root: ""
results_root: ""

# Trainer configuration
epochs: 200
val_freq: 1
key_score_metric: r100
convergence_threshold: 30

# DataLoader configuration
Dataset_type: NodeListDataset
num_workers: 1
NodeListDataset_type: LinkDataset
pos_sampler: ObservedEdges_Sampler
neg_sampler: RandomNeg_Sampler
num_neg: 1
BatchSampleIndicesGenerator_type: SampleIndicesWithReplacement
train_batch_size: 1024
train_edge_sample_ratio: 0.1

# Evaluator configuration
val_evaluator: ""
val_batch_size: 256
file_val_set: ""
test_evaluator: ""
test_batch_size: 256
file_test_set: ""

# Model configuration
model: xGCN
seed: 1999

emb_table_device: "cuda:0"
forward_device: "cuda:0"
out_emb_table_device: "cuda:0"

from_pretrained: 0
file_pretrained_emb: ""
freeze_emb: 1
emb_dim: 64 
emb_init_std: 1.0

loss_type: bpr
L2_reg_weight: 0.0

dnn_lr: 0.001
dnn_arch: "[nn.Linear(64, 1024), nn.Tanh(), nn.Linear(1024, 1024), nn.Tanh(), nn.Linear(1024, 64)]"
use_scale_net: 1
scale_net_arch: "[nn.Linear(64, 32), nn.Tanh(), nn.Linear(32, 1), nn.Sigmoid()]"

num_gcn_layers: 1
stack_layers: 0

renew_by_loading_best: 1
K: 10
T: 3
tolerance: 3
