model: 'xgcn'
train_dl: EdgeBased_Sampling_TrainDataLoader

device: 'cuda:0'
emb_table_device: 'cuda:0'

convergence_threshold: 30
val_freq: 1
key_score_metric: r100
epochs: 300

train_batch_size: 4096
ensure_neg_is_not_neighbor: 0

validation_method: ''
mask_nei_when_validation: 0
file_validation: ''

test_method: ''
mask_nei_when_test: 1
file_test: ''

emb_dim: 64
emb_init_std: 0.1
freeze_emb: 1
from_pretrained: 0
file_pretrained_emb: ''
l2_reg_weight: 0.0

dnn_arch: '[torch.nn.Linear(64, 1024), torch.nn.Tanh(), torch.nn.Linear(1024, 64)]'
use_two_dnn: 0
dnn_lr: 0.001
dnn_l2_reg_weight: 0.0

loss_fn: bpr_loss
num_neg: 1
neg_weight: 1  # bpr_loss: neg_weight == 1

prop_type: 'lightgcn'
num_gcn_layers: 2
stack_layers: 0
# prop_type: 'pprgo'

renew_by_check_val_score: 1
endure: 3
renew_by_loading_best: 1
renew_and_prop_freq: 3
use_numba_csr_mult: 0
max_renew_times: 999999
max_prop_times: 999999
